/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package QL.SanPhamGUI;

import Client.Client;
import DTO.TheLoaiDTO;
import QL.SanPhamGUI.panelSanPham;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author PC
 */
public class chonTheLoai1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form chonTheLoai
     */
    private static panelSanPham pnsp1;
    private static Client client1;
    private suaSanPham ssp1;
    private String MaTL1="";
    private String TenTL1="";
    private doiTuongGUI1 dt1;
    private String MaDT1;
    public chonTheLoai1(suaSanPham ssp, Client client,doiTuongGUI1 dt,panelSanPham pnsp,String MaDT) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        dt1=dt;
        MaDT1=MaDT;
        ssp1=ssp;
        client1=client;
        pnsp1=pnsp;
        setUp();
    }
 

    private ArrayList<TheLoaiDTO> getList(String yeucau) 
    {
        JSONObject json;
        
        switch (yeucau) 
        {
            case "ListTheLoai":
                ArrayList<TheLoaiDTO> list = new ArrayList<>();
                json = new JSONObject(client1.getList(yeucau));
                
                // chuyen mang chuoi sang mang jsonArray
                JSONArray jsonArray = json.getJSONArray("list");
                for (int i = 0; i < jsonArray.length(); i++) 
                {
                    JSONObject tlObject = jsonArray.getJSONObject(i);
                    String MaTL = tlObject.getString("maTL");
                    String TenTL = tlObject.getString("tenTL");
                    int Trangthai = tlObject.getInt("trangThai");
                    // them vao arraylist
                    // xem lai trang thai
                    list.add(new TheLoaiDTO(MaTL, TenTL, Trangthai));
                    
                }
                return list;
        }
                
        return new ArrayList<>();
    }

    // ham thiet lap bang danh sach
    public void setUp() 
    {
        DefaultTableModel model = (DefaultTableModel) jTableTheLoai.getModel();
        model.setRowCount(0);
        for (TheLoaiDTO theloai : getList("ListTheLoai")) 
        {
            System.out.println(theloai.getTrangThai());
            // them tung doi tuong vao bang
            if (theloai.getTrangThai() == 1) 
            {
                System.out.println(theloai.getTenTL());
                model.addRow(new Object[] {theloai.getMaTL(), theloai.getTenTL()});
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTheLoai = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableTheLoai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TL1", "Viễn tưởng"},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTheLoai.setFocusable(false);
        jTableTheLoai.setGridColor(new java.awt.Color(0, 0, 0));
        jTableTheLoai.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jTableTheLoai.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTheLoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTheLoai);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 12, 12));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setText("Hủy");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(43, 22));
        jButton3.setMinimumSize(new java.awt.Dimension(43, 22));
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(43, 22));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(MaTL1.equals("") || TenTL1.equals(""))
       {
           JOptionPane.showMessageDialog(null, "Chua chon doi tuong!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           dt1.list.add(new Object[] {MaTL1,TenTL1});
           JInternalSuaSP jSSP = new JInternalSuaSP(ssp1,client1,MaTL1,TenTL1,dt1,pnsp1,MaDT1);
           ssp1.mainSSP.removeAll();
           ssp1.mainSSP.add(jSSP).setVisible(true);
       }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTableTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTheLoaiMouseClicked
        DefaultTableModel table = (DefaultTableModel) jTableTheLoai.getModel();
        int index = jTableTheLoai.getSelectedRow();
        String MaTL = table.getValueAt(index, 0).toString();
        String TenTL = table.getValueAt(index, 1).toString();
        MaTL1 = MaTL;
        TenTL1 = TenTL;
    }//GEN-LAST:event_jTableTheLoaiMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTheLoai;
    // End of variables declaration//GEN-END:variables
}
